metadata_version=1
application_id=com.shinpstudio.chanriva
variant=release
supabase_project_ref=zgzllmaoyymoeiqtybck
supabase_environment=production
supabase_url=https://zgzllmaoyymoeiqtybck.supabase.co
