/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: b5bf1157242f926dab293b63b1f9eac1)
interface __BaseEnv_Env {
	SUPABASE_URL: "https://zgzllmaoyymoeiqtybck.supabase.co";
	ROOM_REGISTRY: DurableObjectNamespace<import("./src/index").RoomRegistry>;
	ROOM: DurableObjectNamespace<import("./src/index").Room>;
	SOCIAL_REGISTRY: DurableObjectNamespace<import("./src/index").PeopleSocialRegistry>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "RoomRegistry" | "Room" | "PeopleSocialRegistry";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "SUPABASE_URL">> {}
}
