/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 2d1aaa9c99b7536ca253388f4a224b37)
interface __BaseEnv_Env {
	SUPABASE_URL: "https://zgzllmaoyymoeiqtybck.supabase.co";
	ROOM_REGISTRY: DurableObjectNamespace<import("./src/index").RoomRegistry>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "RoomRegistry";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
